# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5d20eda1b06dc9812c60a69f1c50ab66"
name = "shivansh-test-app"
application_url = "https://charleston-accessory-grill-remarkable.trycloudflare.com"
embedded = true
handle = "shivansh-test-app"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_products"

[auth]
redirect_urls = ["https://charleston-accessory-grill-remarkable.trycloudflare.com/auth/callback", "https://charleston-accessory-grill-remarkable.trycloudflare.com/auth/shopify/callback", "https://charleston-accessory-grill-remarkable.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
